export const randomWords = [
  'abacaxi',
  'banco',
  'cachorro',
  'desarrollo',
  'elefante',
  'flor',
  'guitarra',
  'héroe',
  'isla',
  'jardín',
  'kiwi',
  'luna',
  'monstruo',
  'naranja',
  'oasis',
  'pájaro',
  'quinto',
  'rayo',
  'silla',
  'tren',
  'universo',
  'viento',
  'xilófono',
  'yogur',
  'zorro',
  'cielo',
  'estrella',
  'flor',
  'luz',
  'montaña',
  'acantilado',
  'bailar',
  'comida',
  'agua',
  'sombra',
  'sol',
  'noche',
  'día',
  'correr',
  'caminar',
  'futbol',
  'cielo',
  'rosa',
  'rojo',
  'azul',
  'verde',
  'amarillo',
  'blanco',
  'negro',
  'colina',
  'piedra',
  'flor',
  'perfume',
  'corazón',
  'amistad',
  'felicidad',
  'música',
  'pelota',
  'balón',
  'dientes',
  'cuerpo',
  'lucha',
  'guerra',
  'paz',
  'estrella',
  'luna',
  'sol',
  'tierra',
  'mar',
  'agua',
  'viento',
  'roca',
  'camino',
  'bosque',
  'selva',
  'pueblo',
  'ciudad',
  'piedra',
  'luz',
  'viento',
  'invierno',
  'primavera',
  'verano',
  'otoño',
  'tren',
  'carro',
  'bicicleta',
  'avión',
  'barco',
  'bote',
  'piscina',
  'montaña',
  'cima',
  'viento',
  'nieve',
  'lluvia',
  'calor',
  'frío',
  'agua',
  'aceite',
  'taza',
  'vaso',
  'plato',
  'cuchara',
  'tenedor',
  'cuchillo',
  'sal',
  'azúcar',
  'pan',
  'arroz',
  'harina',
  'tortilla',
  'pasta',
  'tomate',
  'lechuga',
  'zanahoria',
  'peine',
  'cepillo',
  'crema',
  'jabón',
  'shampoo',
  'toalla',
  'silla',
  'mesa',
  'cama',
  'lámpara',
  'ventilador',
  'aire',
  'termo',
  'refrigerador',
  'microondas',
  'horno',
  'cocina',
  'cuarto',
  'silla',
  'espejo',
  'ventana',
  'puerta',
  'pared',
  'piso',
  'techo',
  'ventilador',
  'bicicleta',
  'bici',
  'camiseta',
  'zapato',
  'pantalón',
  'falda',
  'sombrero',
  'bufanda',
  'guantes',
  'chaqueta',
  'abrigo',
  'pantalones',
  'calcetines',
  'cartera',
  'bolso',
  'mochila',
  'corbata',
  'gafas',
  'pantalón',
  'cinturón',
  'billetera',
  'teclado',
  'ratón',
  'pantalla',
  'monitor',
  'computadora',
  'teléfono',
  'cámara',
  'batería',
  'cargador',
  'cable',
  'auriculares',
  'altavoz',
  'micrófono',
  'accesorio',
  'puerto',
  'tarjeta',
  'memoria',
  'procesador',
  'tarjeta gráfica',
  'pantalla',
  'escritorio',
  'silla',
  'lámpara',
  'luz',
  'guitarra',
  'piano',
  'bajo',
  'violín',
  'flauta',
  'cello',
  'clarinete',
  'saxofón',
  'percusión',
  'batería',
  'congas',
  'maracas',
  'tambores',
  'piano',
  'guitarra',
  'violín',
  'trompeta',
  'bajo',
  'trompeta',
  'cajón',
  'congas',
  'piano',
  'saxo',
  'concierto',
  'festival',
  'acústica',
  'melodía',
  'canción',
  'grupo',
  'orquesta',
  'melodía',
  'timbre',
  'artista',
  'letra',
  'composición',
  'interpretación',
  'repertorio',
  'piano',
  'cuerdas',
  'sinfónica',
  'charango',
  'técnica',
  'guitarra',
  'estudio',
  'piano',
  'instrumento',
  'bandoneón',
  'cuatro',
  'sitar',
  'conjunto',
  'coro',
  'recital',
  'escenario',
  'músico',
  'solista',
  'compositor',
  'canción',
  'clásica',
  'rock',
  'pop',
  'blues',
  'jazz',
  'bossa',
  'punk',
  'reggae',
  'teatro',
  'cine',
  'danza',
  'actuación',
  'película',
  'comedia',
  'drama',
  'tragedia',
  'musical',
  'espectáculo',
  'arte',
  'escena',
  'escenario',
  'teatro',
  'ballet',
  'interpretación',
  'guion',
  'actriz',
  'actor',
  'producción',
  'director',
  'película',
  'cortometraje',
  'documental',
  'festival',
  'crítica',
  'reparto',
  'ensayo',
  'casting',
  'iluminación',
  'decorado',
  'sonido',
  'set',
  'cámara',
  'video',
  'graba',
  'video',
  'dirección',
  'escena',
  'drama',
  'comedia',
  'actor',
  'directores',
  'actriz',
  'protagonista',
  'serie',
  'episodio',
  'telenovela',
  'doblaje',
  'banda sonora',
  'ensayo',
  'guion',
  'producción',
  'documental',
  'película',
  'comedia',
  'actuación'
]

export const phrases = [
  'El deseo es el fuego que aviva el alma, un llamado silencioso que invita a explorar lo desconocido, donde cada roce es un universo esperando ser descubierto.',
  'Tu piel es un mapa que narra historias que jamás fueron contadas, y en cada caricia se dibuja un verso que el tiempo no puede borrar.',
  'Amar es perderse en el abismo de otra alma, donde la lógica no tiene lugar y solo queda el lenguaje de las miradas y los silencios compartidos.',
  'Tu mirada es un laberinto en el que perderme se siente como encontrar el verdadero sentido de mi existencia, un lugar donde el tiempo deja de importar.',
  'El amor no busca poseer, sino liberar. En tu abrazo, encuentro la paradoja de ser completamente mío y, al mismo tiempo, completamente tuyo.',
  'Cada beso es un puente entre dos almas que desean fundirse en una sola, un instante eterno donde el mundo desaparece y solo queda el lenguaje del alma.',
  'El deseo no es solo físico; es el eco de un llamado del alma que busca en la otra su reflejo más puro y eterno.',
  'Tus caricias no solo tocan mi piel; despiertan partes de mi alma que desconocía. En cada roce, dejo de ser quien era para convertirme en quien soy contigo.',
  'La pasión es la energía que transforma lo cotidiano en extraordinario. Tus labios son la chispa que enciende mi fuego y me recuerda que estoy vivo.',
  'El amor verdadero no ata, libera. Es un vuelo compartido hacia lo desconocido, donde las alas de uno se completan con las del otro.',
  'Eres el caos perfecto que da sentido a mi existencia. En tu mirada, encuentro las respuestas a preguntas que no sabía que tenía.',
  'La lujuria no es pecado cuando se mezcla con el alma. Es el arte de conectar lo carnal con lo eterno, lo fugaz con lo infinito.',
  'En tu risa, encuentro la música que mi alma necesita para bailar. Cada sonido que emites es un himno a la vida y al amor.',
  'Tus ojos son un portal a mundos que jamás soñé explorar. En ellos, el universo entero parece caber, y yo deseo perderme en su profundidad.',
  'La eternidad no está en el tiempo, sino en los momentos que vivimos con intensidad. Contigo, cada instante se convierte en un pedazo de infinito.',
  'Tu voz es como un susurro del universo, un recordatorio de que lo divino existe en lo humano, de que lo infinito cabe en una palabra.',
  'El deseo no entiende de lógica ni de razones; es un instinto primitivo que nos conecta con lo más puro de nuestra existencia, contigo como mi epicentro.',
  'Amar es desnudarse más allá de lo físico, es mostrar el alma en su forma más vulnerable y confiar en que el otro la cuidará con ternura.',
  'Tus besos son la llave que abre puertas a mundos que creía cerrados. Cada encuentro contigo es una explosión de colores en mi universo gris.',
  'El amor no busca perfección; busca autenticidad. Contigo, lo imperfecto se convierte en poesía, y lo cotidiano, en arte puro que deseo contemplar eternamente.',
  'Tu tacto es un lenguaje sin palabras que habla directamente al alma. Cada caricia tuya es un poema que se escribe sobre mi piel y mi espíritu.',
  'El placer es la alquimia del alma, un instante donde cuerpo y espíritu se encuentran en perfecta armonía, como en cada susurro que compartimos.',
  'Tu esencia es mi brújula en este vasto mar de incertidumbres. En cada beso tuyo, encuentro la dirección hacia mi verdadero norte, hacia lo que realmente importa.',
  'Eres la chispa que incendia mi mundo. En tus manos, lo mundano se convierte en mágico, y en tus ojos, encuentro el reflejo de mi alma desnuda.',
  'Amar no es encontrar a alguien que nos complete, sino a alguien que nos inspire a ser más de lo que jamás imaginamos. Contigo, soy infinito.',
  'Tu perfume no solo envuelve mi cuerpo; penetra mi alma, dejando huellas imborrables que me recuerdan que lo esencial no se ve, pero se siente profundamente.',
  'El amor es el lenguaje del universo, y contigo, cada palabra que no digo se transforma en poesía que solo tú puedes entender.',
  'Tus caricias son la melodía que mi cuerpo necesita para vibrar. En cada toque, siento el ritmo de una danza eterna entre nuestras almas.',
  'El deseo es un puente entre lo carnal y lo divino. En tu abrazo, encuentro la unión de lo terrenal con lo celestial, de lo fugaz con lo eterno.',
  'Tu sonrisa es el amanecer que ilumina mis días. En ella, encuentro la promesa de que incluso en la oscuridad, siempre hay luz para guiarme.',
  'La pasión no se busca; se encuentra en el momento más inesperado, como el instante en que tus ojos se cruzaron con los míos y encendieron mi ser.',
  'Eres mi musa y mi tormento, el fuego que arde en mi interior y me recuerda que vivir es sentir cada emoción con intensidad.',
  'Tu abrazo es mi refugio, el lugar donde mi alma encuentra paz y mi cuerpo, el calor que solo el amor verdadero puede dar.',
  'El amor no es un destino, sino un viaje. Contigo, cada paso es un descubrimiento, y cada tropiezo, una oportunidad de crecer juntos.',
  'Tus palabras son la lluvia que moja mi desierto interior. En cada frase, siento que mi alma florece y encuentra sentido en lo que antes parecía vacío.',
  'El deseo es el lenguaje que nuestras almas usan para comunicarse cuando las palabras no alcanzan. En cada mirada tuya, escucho ese idioma que solo tú y yo entendemos.',
  'Eres el poema que nunca termino de escribir, la inspiración que mi alma necesita para crear y el motivo por el que creo que lo eterno existe.',
  'La lujuria es la energía que nos conecta con nuestra esencia más pura. En tus labios, encuentro la chispa que enciende mi fuego interno.',
  'Amar es entregarse sin reservas, es confiar en que el otro cuidará nuestro corazón como si fuera el suyo. En ti, confío mi ser sin miedo.',
  'Tu piel guarda historias que deseo leer con mis manos. Cada caricia es una palabra, y juntos escribimos un libro que el tiempo no podrá borrar.',
  'El amor no se entiende, se siente. Contigo, cada emoción es un recordatorio de que lo más hermoso de la vida no necesita explicación.',
  'Tus ojos son el espejo en el que veo mi alma reflejada. En ellos, descubro que lo divino existe y que el amor es su lenguaje universal.',
  'Eres mi tormenta y mi calma, el caos que me desarma y la paz que me reconstruye. En ti, encuentro el equilibrio que mi vida necesita.',
  'El deseo es la fuerza que nos mueve hacia lo desconocido. En tus brazos, encuentro el coraje para explorar los rincones más profundos de mi ser.',
  'Tus besos son la promesa de un paraíso que solo existe contigo. En cada roce, siento que el cielo desciende para encontrarse con mi alma.',
  'El amor no tiene forma, pero contigo lo siento tangible. En tus caricias, descubro que lo invisible puede ser tan real como el aire que respiro.',
  'Eres el fuego que calienta mi invierno, el faro que guía mi barco en la tormenta. Contigo, lo imposible se convierte en realidad palpable.',
  'Tu voz es como un eco del universo que resuena en mi interior. En cada palabra, siento que las estrellas conspiran para unirnos más allá del tiempo.',
  'Cada suspiro que nace en tus labios se convierte en una brisa que acaricia mi alma, un recordatorio de que el amor es el lenguaje más puro del universo.',
  'Tus caricias son más que un roce; son el mapa que guía mi espíritu hacia el infinito, un camino donde la razón y el deseo se encuentran en perfecta armonía.',
  'En el calor de tu abrazo, encuentro refugio para mis miedos y la fuerza para enfrentar lo desconocido, porque tu amor es mi ancla y mi vuelo.',
  'Tu mirada es un abismo en el que me lanzo sin miedo, porque en su profundidad descubro el sentido de la vida y la conexión de dos almas errantes.',
  'El deseo es el eco del universo que nos recuerda que estamos vivos, y contigo, cada instante es una explosión de sentidos que trasciende lo mundano.',
  'El roce de tu piel es un poema sin palabras que recita mi cuerpo en silencio. En cada línea, encuentro el sentido del amor y la eternidad.',
  'Amar es entregarse sin reservas, sin miedos. En tu sonrisa, encuentro la valentía de desarmar mis murallas y ser completamente yo.',
  'Eres la melodía que mi alma anhela escuchar, la nota perfecta que transforma el ruido del mundo en una sinfonía de amor y deseo eterno.',
  'Cada beso que compartimos es un pacto silencioso entre nuestras almas, un recordatorio de que, aunque efímeros, podemos ser eternos en cada instante juntos.',
  'Tu risa ilumina mi oscuridad, es el fuego que enciende mi esperanza y el canto que acompaña a mi espíritu en su danza con el universo.',
  'El amor no es poseer, es admirar. En ti, encuentro la belleza de ser testigo del milagro de tu existencia sin intentar cambiar ni un ápice de tu esencia.',
  'El deseo no se explica; se vive. En cada caricia tuya, siento la verdad que no necesita palabras, solo la intensidad de un instante compartido.',
  'Tus labios son la llave que abre el portal hacia mundos desconocidos. En cada beso, descubro universos que solo existen en el roce de nuestras almas.',
  'El amor verdadero no se encuentra, se construye. Contigo, cada mirada y cada palabra son ladrillos en el puente que une nuestras almas eternamente.',
  'En tus ojos, veo el reflejo de un mundo donde lo humano se encuentra con lo divino, donde el amor trasciende el tiempo y la lógica.',
  'Tu piel es el lienzo donde mis manos pintan los sueños más profundos de mi alma. Cada caricia es un trazo que narra nuestra historia.',
  'El deseo no es solo físico; es la danza de dos espíritus que se buscan en un universo caótico y encuentran paz en la conexión mutua.',
  'Tu abrazo es el templo donde mi alma encuentra paz. En el calor de tus brazos, el tiempo se detiene y la eternidad cobra sentido.',
  'Eres el sol que ilumina mis días y la luna que calma mis noches. En tu presencia, el mundo parece girar al ritmo de nuestro amor.',
  'El amor no se mide en palabras ni en gestos; se siente en el alma. Contigo, mi espíritu encuentra la paz que siempre buscó.',
  'Tus besos son la promesa de una eternidad compartida, el eco de un amor que trasciende lo físico y se instala en lo más profundo del ser.',
  'Eres mi tormenta y mi calma, el caos que desordena mi mundo y la paz que lo reconstruye. En ti, encuentro todo lo que mi alma busca.',
  'Tu voz es el canto que mi espíritu necesita para volar. En cada palabra, siento la fuerza del universo susurrándome que todo es posible contigo.',
  'El amor no tiene lógica, y esa es su magia. En tus brazos, dejo de lado la razón y me entrego al milagro de ser completamente humano.',
  'Eres el misterio que nunca quiero resolver, el enigma que mi alma desea descifrar cada día, porque en tu complejidad encuentro mi propósito.',
  'El deseo es la chispa que enciende la conexión entre dos almas. En cada caricia tuya, siento la verdad de que somos más que materia.',
  'Tus ojos son como un océano en el que me sumerjo sin miedo, porque en su profundidad encuentro el refugio y la libertad que mi espíritu anhela.',
  'El amor no busca perfección, sino autenticidad. Contigo, cada defecto se convierte en arte, y cada momento, en una obra maestra compartida.',
  'Eres la inspiración que transforma mi mundo. En cada mirada tuya, descubro que la vida es más que sobrevivir; es vivir intensamente contigo.',
  'Tus caricias son el lenguaje que mi cuerpo entiende sin palabras. En cada toque, siento la poesía del universo expresándose a través de ti.',
  'Amar es confiar en el otro incluso cuando no entendemos sus silencios. En tu mirada, encuentro las respuestas que las palabras no pueden darme.',
  'El deseo es un fuego que consume lo superficial para revelar lo esencial. En tu abrazo, encuentro la verdad de lo que significa realmente estar vivo.',
  'Tu presencia es el regalo más grande que mi alma podría recibir. En cada instante contigo, siento que la eternidad no es un concepto, sino un hecho.',
  'El amor es un acto de valentía. Contigo, dejo atrás mis miedos y me lanzo al abismo de sentir con toda la intensidad de mi ser.',
  'Eres el faro que guía mi camino en la tormenta. En tu luz, encuentro la fuerza para seguir adelante y la calma para disfrutar del momento.',
  'Tus besos son el portal que conecta mi alma con el infinito. En ellos, siento que el tiempo se detiene y el amor trasciende todo límite.',
  'El amor no es un destino; es el viaje. En cada paso contigo, descubro nuevas formas de ser y sentir que jamás imaginé posibles.',
  'Tus palabras son la lluvia que moja mi desierto interior. En cada frase, siento que mi alma florece y se llena de vida nueva.',
  'El deseo no conoce límites ni barreras. En cada caricia tuya, siento que el universo entero conspira para que estemos juntos, aquí y ahora.',
  'Eres el sueño que no quiero despertar, el anhelo que hace que mi espíritu vuele más alto y más libre que nunca.',
  'El amor no es perfecto, pero contigo, cada imperfección se convierte en la pieza que completa mi vida y da sentido a todo lo demás.',
  'Tus ojos son la ventana al paraíso que siempre imaginé. En ellos, veo el reflejo de un mundo donde solo existimos tú y yo.',
  'El deseo es la fuerza que une lo tangible con lo eterno. En tus labios, encuentro la conexión entre mi cuerpo y mi alma.',
  'Tu sonrisa es la luz que ilumina mi oscuridad. En ella, encuentro la esperanza de que el amor verdadero no solo existe, sino que vive en ti.',
  'El amor no necesita explicaciones. En tu abrazo, encuentro todas las respuestas a las preguntas que jamás me atreví a hacer.',
  'Eres el poema que mi alma necesita para sentirse completa. En cada palabra que compartimos, siento la magia de lo eterno en lo efímero.',
  'Tu piel es el lienzo donde mis manos dibujan la historia de nuestro amor. Cada caricia es un capítulo que el tiempo no podrá borrar.',
  'Amar es ver al otro con los ojos del alma. Contigo, veo la belleza de la vida reflejada en cada gesto y cada mirada.'
]

export const seductionPhrases = [
  '¿Sabías que solo el 3% de las personas pueden mantener contacto visual por más de 8 segundos sin parpadear? Vamos a ver si eres parte de ese grupo.',
  'Tienes una vibra interesante, pero estoy tratando de descifrar si eres más del tipo aventurero o del que prefiere noches tranquilas con un buen libro.',
  'Algo en tu sonrisa me dice que tienes un secreto interesante. ¿Debería adivinar o vas a contármelo directamente?',
  'No suelo acercarme a desconocidas, pero algo en tu energía me hizo pensar que eres diferente al resto. ¿Siempre tienes esa aura magnética?',
  'Eres intrigante. ¿Eres tan fascinante como aparentas o simplemente muy buena en crear misterio?',
  'Creo que las personas más interesantes siempre tienen una historia inesperada. ¿Cuál es la tuya?',
  '¿Qué es lo más atrevido que has hecho este mes? Parece que tienes una chispa rebelde.',
  'Tengo una teoría: las personas con una mirada como la tuya son de las que tienen aventuras épicas. ¿Estoy en lo correcto?',
  'No sé por qué, pero algo me dice que si nos conociéramos más, terminaríamos planeando un viaje espontáneo a un lugar exótico.',
  'Tu estilo me recuerda a alguien que no se conforma con lo ordinario. ¿Siempre buscas algo fuera de lo común?',
  'La forma en que hablas tiene algo hipnotizante. ¿Siempre es así, o estoy cayendo en tu juego?',
  "Te vi y pensé: 'Ella tiene esa vibra que hace que cada lugar se sienta más vivo'. ¿Lo haces a propósito?",
  'Apuesto a que tienes una playlist secreta que define tu personalidad. ¿Qué canción sería tu introducción en una película?',
  'Estoy intentando decidir si eres más de sorprender o de ser sorprendida. ¿Qué dices tú?',
  'Tienes algo especial en tu forma de moverte, como si supieras que el mundo está mirándote. ¿Es natural o lo ensayas?',
  'Tu energía es como un imán. Creo que las personas se sienten atraídas a ti sin saber exactamente por qué. ¿Es parte de tu encanto?',
  'Eres como ese libro raro en una biblioteca que nadie más encuentra. ¿Debería sentirme afortunado por haberte visto?',
  '¿Sabías que la mayoría de las conexiones profundas empiezan con una pregunta inesperada? Vamos a probarlo: ¿Qué superpoder elegirías y por qué?',
  'Tienes una presencia que hace que la gente quiera saber más de ti. ¿Eres consciente de eso o simplemente ocurre?',
  'Tu mirada tiene una intensidad única. Me pregunto qué es lo que estás pensando cuando observas el mundo.',
  '¿Siempre eres tan confiada o es solo porque sabes que todo el lugar está notándote ahora mismo?',
  'Me pareció curioso algo: hay un aura en ti que no todos tienen. ¿Eres del tipo que se arriesga sin pensarlo dos veces?',
  'No suelo hacer esto, pero sería un error no saludarte. Algo me dice que hay algo interesante que aprender de ti.',
  'Pareces de esas personas que tienen un talento oculto que nadie esperaría. ¿Es cierto o es solo intuición?',
  'Si estuviéramos en una película, creo que serías el personaje que todos recuerdan aunque solo aparece en la escena final.',
  '¿Sabías que las personas más interesantes siempre tienen una mezcla de locura y lógica? Tú pareces tener esa mezcla perfecta.',
  'Tu sonrisa tiene algo travieso. Me pregunto cuántos problemas pequeños has causado con ella.',
  'Hay algo en ti que grita autenticidad. ¿Siempre has sido de esas personas que no siguen el molde?',
  'Si pudiera leer tu mente ahora, ¿qué encontraría? Parece que tienes algo interesante rondando ahí.',
  'Apuesto a que eres la persona que siempre tiene algo inesperado que decir. ¿Cuál es el último pensamiento extraño que tuviste?',
  '¿Eres siempre así de intrigante o estoy viendo una faceta reservada solo para momentos especiales?',
  'Pareces de esas personas que saben exactamente lo que quieren. ¿Estoy en lo correcto o te gusta sorprenderte?',
  'Tienes esa vibra de alguien que podría transformar un día normal en una aventura inolvidable. ¿Te ocurre seguido?',
  '¿Sabías que las personas con miradas como la tuya suelen tener un lado rebelde? ¿Es tu caso?',
  'Tienes una presencia que llama la atención, pero no de manera obvia. ¿Es algo natural o te lo propones?',
  'Si fueras un personaje en un libro, serías la protagonista que rompe las reglas. ¿Es una descripción acertada?',
  'Tu manera de hablar tiene un ritmo cautivador. ¿Siempre es así o solo cuando alguien logra captar tu interés?',
  'Te vi y pensé: ‘Esa persona tiene historias que podrían llenar un libro’. ¿Qué título le pondrías?',
  'Tienes un aire de misterio que es imposible ignorar. ¿Es tu estrategia para que la gente quiera conocerte más?',
  'Pareces de esas personas que siempre tienen un plan inesperado. ¿Cuál fue el último giro loco que diste en tu vida?',
  'Tu forma de mirar es como si desafiaras a los demás a descifrarte. ¿Eres tan enigmática como pareces?',
  'Eres como una obra de arte que siempre tiene un detalle nuevo por descubrir. ¿Es esa la vibra que quieres transmitir?',
  'Tu energía me recuerda a esas películas donde la protagonista siempre tiene el control de la escena. ¿Es intencional?',
  'Algo en ti grita independencia, pero también tienes ese toque que invita a las conexiones profundas. ¿Es tu equilibrio natural?',
  'Si tuvieras que describir tu vida como un género de película, ¿cuál sería? Tienes la vibra de un thriller con toques de romance.',
  'A veces, las personas más interesantes son las que más secretos guardan. ¿Cuántos secretos ocultas detrás de esa sonrisa?',
  'Tu aura es como un faro en la oscuridad, atrayendo miradas sin esfuerzo. ¿Siempre has tenido ese efecto en la gente?',
  'Tienes una energía que hace que cualquier lugar se sienta más vibrante. ¿Es algo que has cultivado o simplemente eres así?',
  'Me pregunto si siempre eres el centro de atención o solo cuando decides que el momento lo amerita.',
  'Tu manera de hablar tiene algo hipnótico. ¿Es un don natural o una herramienta de seducción que manejas con maestría?',
  '¿Siempre traes esta energía eléctrica contigo, o es algo que solo aparece en situaciones especiales?',
  'Tu forma de estar aquí me hace pensar que tienes historias que podrían cambiar mi perspectiva. ¿Es cierto?',
  'Pareces alguien que podría conquistar cualquier lugar. ¿Siempre has tenido esa confianza natural?',
  'Si tu vida fuera una canción, ¿sería más rock desenfrenado o una balada intensa?',
  'Tu sonrisa parece esconder un desafío. ¿Siempre es así de intrigante conocerte?',
  'Hay algo en tu forma de mirar que hace que la gente quiera confiar en ti. ¿Lo usas como ventaja?',
  'Tienes ese aire de persona que sabe exactamente cómo iluminar un lugar. ¿Cómo lo haces?',
  'Parece que donde tú estás, pasan cosas interesantes. ¿Es casualidad o un talento especial?',
  '¿Sabes que la gente rara vez se atreve a ser auténtica? Tú pareces desafiar esa norma.',
  'Si te dieran un millón de dólares por hacer algo inesperado esta noche, ¿qué harías?',
  'Tu energía es tan vibrante que hace que este lugar se sienta menos rutinario. ¿Te das cuenta de ese impacto?',
  'Creo que siempre hay una historia divertida detrás de personas interesantes. ¿Cuál es la tuya?',
  'Tu estilo me dice que no sigues reglas, pero tu postura dice que sabes cuáles romper. ¿Estoy en lo cierto?',
  'Si tu personalidad fuera un cóctel, ¿qué ingredientes tendría y qué tan fuerte sería?',
  'Algo en ti grita libertad, pero de una manera que invita a otros a seguirte. ¿Es tu secreto?',
  'Pareces alguien que siempre tiene algo diferente que ofrecer. ¿Cuál es tu habilidad más inesperada?',
  '¿Alguna vez te has detenido a notar cómo haces que todo a tu alrededor parezca más vibrante?',
  'Tu presencia me hace pensar en alguien que siempre tiene un plan alternativo. ¿Qué tan cierto es eso?',
  'Hay algo en tu manera de moverte que hace pensar que tienes un propósito claro. ¿Es verdad o solo una ilusión?',
  '¿Siempre eres así de magnética, o es algo que depende de quién te rodea?',
  'Tu manera de escuchar parece más profunda que la mayoría. ¿Siempre buscas entender antes que juzgar?',
  'Si te dieran un boleto de avión para cualquier lugar ahora mismo, ¿adónde irías sin pensarlo?',
  'Tu aura tiene algo que mezcla calma con una chispa de peligro. ¿Es parte de tu personalidad o de tu encanto?',
  'Algo en tu energía me dice que amas la aventura. ¿Cuál fue la última vez que hiciste algo que te aceleró el corazón?',
  'Si solo pudieras contar una historia para que alguien entienda quién eres, ¿cuál sería?',
  'Tienes esa vibra de alguien que ha vivido cosas que otros ni siquiera imaginan. ¿Es cierto o solo mi percepción?',
  'Pareces alguien que podría transformar lo ordinario en algo extraordinario con solo estar presente. ¿Te lo han dicho antes?',
  'Tienes una forma peculiar de iluminar un lugar. ¿Es algo que siempre has tenido o lo descubriste con el tiempo?',
  'Siempre he creído que las personas más fascinantes tienen una mezcla de caos y calma. ¿Dónde caes tú en ese espectro?',
  '¿Eres del tipo que siempre sigue su instinto, o prefieres pensar todo dos veces antes de actuar?',
  'Algo en tu postura me dice que sabes más de lo que aparentas. ¿Es una táctica o simplemente natural?',
  'Si tu vida fuera un libro, creo que sería difícil de cerrar. ¿Qué título le pondrías?',
  'Tu forma de hablar es como una melodía que se queda en la mente. ¿Siempre es así de envolvente?',
  '¿Te has dado cuenta de cómo haces que cada persona a tu alrededor quiera saber más de ti?',
  'Pareces alguien que podría encontrar aventura en cualquier lugar. ¿Es algo que buscas activamente o simplemente pasa?',
  'Me intriga cómo logras combinar misterio y confianza de una manera tan natural. ¿Es tu superpoder?',
  'A veces, la gente tiene un brillo especial que no se puede ignorar. Tú pareces tenerlo en exceso. ¿Cómo lo manejas?',
  'Tu presencia hace que todo aquí parezca más interesante. ¿Siempre has tenido ese efecto?',
  'Si fueras un color, creo que serías algo inesperado como un dorado oscuro. ¿Cómo te definirías tú?',
  'Pareces alguien que siempre sabe cómo encontrar lo extraordinario en lo ordinario. ¿Es tu forma de ver la vida?',
  'Tu mirada tiene una intensidad que pocas personas pueden igualar. ¿Es una ventana a quién eres realmente?',
  'Me pregunto si siempre eres el alma de la fiesta o si solo eliges serlo cuando quieres.',
  'Tu manera de expresarte tiene algo que invita a confiar. ¿Es un talento natural o lo has perfeccionado?',
  'Tienes un equilibrio entre seguridad y misterio que no se ve todos los días. ¿Es parte de tu estrategia?',
  'Hay algo en tu presencia que hace que la gente quiera quedarse cerca. ¿Es intencional o simplemente ocurre?',
  'Si tu personalidad fuera un viaje, ¿sería más como una carretera costera o un camino salvaje en la montaña?',
  'Tu sonrisa tiene algo hipnótico que me hace pensar que hay más de lo que parece. ¿Qué escondes?',
  '¿Alguna vez alguien te ha dicho que pareces una musa que inspira historias? Porque lo haces.',
  'Tu energía es como un imán, pero no cualquiera puede descifrar el porqué. ¿Cuál es tu secreto?'
]
